# Generated by Django 5.1.2 on 2024-10-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postincategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
